---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-metadata-api-{{ .Values.environmentName }}"
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: "fb-metadata-api-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-metadata-api-{{ .Values.environmentName }}"
        appGroup: "fb-metadata-api"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      containers:
      - name: "fb-metadata-api-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-metadata-api:{{ .Values.circleSha1 }}"
        {{- if ((.Values.resources).requests) }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "10"]
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-metadata-api-config-map
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: ENCODED_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                key: encoded_private_key
          # secrets created by terraform
          # which may or may not depend on values
          # canonically defined in secrets.tfvars
          # Some assets aren't loading properly yet
          # ...maybe an issue with how they're referenced,
          # maybe something else - re-enabled this later
          #
          # Created by cloud-platforms-environments
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-metadata-api-{{ .Values.environmentName }}
                key: url
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: PLATFORM_ENV
            value: {{ .Values.environmentName }}
      volumes:
        - name: tmp-files
          emptyDir: {}
