apiVersion: v1
kind: Secret
metadata:
  name: fb-metadata-api-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-saas-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  encoded_private_key: {{ .Values.encoded_private_key }}
  sentry_dsn: {{ .Values.sentry_dsn }}
