version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: security
          command: docker-compose run --rm metadata-app bundle exec brakeman -q --no-pager
      - run:
          name: test
          command: make spec
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-metadata-api
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - a9:9c:0f:a2:2f:77:41:80:b8:84:e0:c8:10:a4:eb:2e
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_a99c0fa22f774180b884e0c810a4eb2e" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test
          environment:
            APPLICATION_NAME: fb-metadata-api
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-saas-test
          command: './deploy-scripts/bin/deploy'
      - slack/status:
          only_for_branches: main
          success_message: ":rocket:  Successfully deployed to Test  :guitar:"
          failure_message: ":alert:  Failed to deploy to Test  :try_not_to_cry:"
          include_job_number_field: false
  remove_acceptance_tests_services:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: remove acceptance tests services
          command: 'bundle exec rake remove_acceptance_tests_services'
      - slack/status: *slack_status

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only:
                - main
  remove_acceptance_tests_services:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - remove_acceptance_tests_services
