apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fb-metadata-api-cron-remove-acceptance-services-test
  namespace: formbuilder-saas-test
spec:
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "fb-metadata-api-test"
            image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-metadata-api:{{ .Values.circleSha1 }}"
            args:
            - /bin/sh
            - -c
            - bundle exec rails remove_acceptance_tests_services
            securityContext:
              runAsUser: 1001
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: fb-metadata-api-config-map
            env:
              - name: SENTRY_CURRENT_ENV
                value: test
              - name: SECRET_KEY_BASE
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-test
                    key: secret_key_base
              - name: ENCODED_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-test
                    key: encoded_private_key
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: rds-instance-formbuilder-metadata-api-test
                    key: url
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-test
                    key: sentry_dsn
          restartPolicy: Never
