apiVersion: v1
kind: Secret
metadata:
  name: fb-metadata-api-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-saas-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
